CREATE TABLE IF NOT EXISTS config (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, campeonatoAno TEXT,homenageado TEXT,tema TEXT,dataAtualizacao TEXT,versaoAtualizacao TEXT);
CREATE TABLE IF NOT EXISTS artilheiros (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, nome TEXT,gols TEXT,equipe TEXT,numero TEXT,posicao TEXT,categoria TEXT,cartoesAmarelos TEXT,cartoesVermelhos TEXT);
CREATE TABLE IF NOT EXISTS cartoes_amarelos (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, equipe TEXT,numero TEXT,jogador TEXT,data TEXT,tempo TEXT,adversario TEXT,arbitro TEXT);
CREATE TABLE IF NOT EXISTS cartoes_vermelhos (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, equipe TEXT,numero TEXT,jogador TEXT,data TEXT,tempo TEXT,adversario TEXT,arbitro TEXT);
CREATE TABLE IF NOT EXISTS jogos (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, data TEXT,horario TEXT,equipe1 TEXT,golsEquipe1 TEXT,equipe2 TEXT,golsEquipe2 TEXT,cartoesAmarelos TEXT,cartoesVermelhos TEXT,totalCartoes TEXT,categoria TEXT,arbitro TEXT,assistente1 TEXT,assistente2 TEXT,notaArbitroMedia TEXT,notaArbitroEquipe1 TEXT,notaArbitroEquipe2 TEXT,rodada TEXT,turno TEXT,vencedor TEXT);
CREATE TABLE IF NOT EXISTS tabela (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, rodada TEXT,turno TEXT,data TEXT,horario TEXT,equipe1 TEXT,equipe2 TEXT,categoria TEXT);
CREATE TABLE IF NOT EXISTS suspensos (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, equipe TEXT,jogador TEXT,numero TEXT,categoria TEXT,criterio TEXT,jogos TEXT,motivo TEXT);
CREATE TABLE IF NOT EXISTS classificacao_4as_finais (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, posicao TEXT,equipe TEXT,pontosGanhos TEXT,jogos TEXT,vitorias TEXT,empates TEXT,derrotas TEXT,golsPro TEXT,golsContra TEXT,saldoGols TEXT,categoria TEXT,grupo TEXT);
CREATE TABLE IF NOT EXISTS classificacao_geral (id INTEGER PRIMARY KEY AUTOINCREMENT, campos TEXT, equipe TEXT,pontosGanhos TEXT,jogos TEXT,vitorias TEXT,empates TEXT,derrotas TEXT,golsPro TEXT,golsContra TEXT,saldoGols TEXT,cartoesAmarelos TEXT,cartoesVermelhos TEXT);
